PROJNAME=LED_display
DEVICE=CY8C22345
BASEDEVICE=CY8C22045
PROJPATH=E:/430PRO~1/PM2~1.5_L/LED_DI~1/LED_DI~1
PSOCDIR=D:/Cypress/PSOCDE~1/5.4/Common/CY110F~1
INCLUDE_PATH=D:/Cypress/PSOCDE~1/5.4/Common/CY110F~1/tools/include/CY8C22~1
CSRCS= boardcommunication.c led.c main.c particlesensor.c si7020.c software_iic.c t74hc595.c
LIBCSRCS=
STDCSRCS=
ASMSRCS=
LIBASMSRCS= psocconfig.asm psocconfigtbl.asm sar10.asm sar10int.asm timer16.asm timer16int.asm timer8.asm timer8int.asm uart_board.asm uart_boardint.asm uart_boardplus.asm uart_sensor.asm uart_sensorint.asm uart_sensorplus.asm
STDASMSRCS=
OBJECT_SOURCES= boardcommunication.c led.c main.c particlesensor.c si7020.c software_iic.c t74hc595.c
FILLVALUE=0x30
LASTROM=0x3fff
HI-TECHDIR=C:\PROGRA~2\HI-TEC~1\HCPSOC\PRO\9.61
LASTRAM=0x3ff
MORE_CFLAGS=--WARN=0  --OPT=asm,9 
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
SYS_INC_CONTENTS:=IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_HITECH SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 SYSTEM_STACK_PAGE:_equ_3 SYSTEM_STACK_PAGE_OFFSET:_equ_0 
SYSTEM_TOOLS=2
CONFIG_NAMES=led_display 
